### ISSUE TITLE
Грешен изходен пример на задача 

### ISSUE THREAD

**Issue by gkrastenov** [destroierdam/Intro-to-Programming-IS-2019#1]
На трета задача примера с масив { 2.1,0,9.9,3,1,-1,4.5,7 } трябва да изкара на конзолата 3 -> 3 * 1, а не както е в момента 21, защото 7 е по-голямо от 4.5.
https://github.com/destroierdam/Intro-to-Programming-IS-2019/blob/master/Dopulnitelno/I_Kontrolno/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8.pdf?fbclid=IwAR1MFwJkP7KP7b8eWiHbxqp5snu_co9F2IUKmmkr029do3Xc6NmvX-SnuGE

**Comment by destroierdam** [comment]
Благодаря! Оправено е.
